import localFont from "next/font/local";
import "./globals.css";
import ClientWrapper from "@/ClientWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: `Metronic - the world's #1 selling Bootstrap Admin Theme Ecosystem for HTML, Vue, React, Angular &amp; Laravel by Keenthemes`,
  description: "Generated by create next app",
  // Preload links
  keywords: "your, keywords, here",
  // You can add other metadata as needed
  openGraph: {
    images: [
      "https://image.tmdb.org/t/p/w185/k42Owka8v91trK1qMYwCQCNwJKr.jpg",
      "https://allmovieshub.gay/wp-content/uploads/2024/10/kWNCRgt3ocv19bYO0sk7ui5i89iy5iy9i89889yiy.webp",
      "https://moviesrock.pro/wp-content/uploads/2024/10/kWNCRgt3ocv19bYO0sk7ui5i89iy5iy9i89889yiy.webp",
      "https://allmovieshub.gay/wp-content/uploads/2024/09/imadfdge.png",
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased home blog wp-custom-logo dark-background dark-version main-layout-boxed disable-floating-video header-vid-default beeteam368 elementor-default elementor-kit-12 header-fixed header-tablet-and-mobile-fixed toolbar-enabled toolbar-fixed aside-enabled aside-fixed`}
      >
        <ClientWrapper>
          {children}
        </ClientWrapper>
      </body>
    </html>
  );
}
