import React from 'react'
export const metadata = {
  title: "Admin - Metronics",
  description: "Generated by create next app",
};
export default function layout({ children }) {
  return (
    <>
      {children}
    </>
  )
}